---

- hosts: local
  become: true
  become_user: root
  vars_prompt:
    - name: wifi_ssid
      prompt: WiFi SSID
      private: false
    - name: wifi_password
      prompt: WiFi Password
  roles:
    - role: setup-sdcard
