---

- hosts: local
  become: yes
  become_user: root
  vars_prompt:
  - name: wifi_ssid
    prompt: WiFi SSID
    private: no
  - name: wifi_password
    prompt: WiFi Password
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - role: setup-sdcard
